name: "validate"

on:
  pull_request_target:
    branches: [ "master" ]
    types: [ "opened", "synchronize", "ready_for_review" ]
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  get-php-info:
    name: "Get PHP Info"
    runs-on: ubuntu-latest
    outputs:
      extensions: ${{ steps.php-info-matrix.outputs.extensions }}
      versions: ${{ steps.php-info-matrix.outputs.version }}
      lowest-version: ${{ steps.php-info-matrix.outputs.lowest }}
    steps:
      - uses: actions/checkout@v4
      - id: php-info-matrix
        uses: WyriHaximus/github-action-composer-php-versions-in-range@v1


  validate-user-permissions:
    runs-on: ubuntu-latest
    name: "Validate User Permissions"
    steps:
      - name: "Get user permissions"
        id: userPermissions
        uses: actions-cool/check-user-permission@v2
        with:
          require: "write"
          username: ${{ github.triggering_actor }}
      - name: "Check user permissions"
        if: steps.userPermissions.outputs.check-result == 'false'
        run: |
          echo "${{ github.triggering_actor }} does not have 'write' permission on this repo."
          echo "Originally triggered by ${{ github.actor }}"
          exit 1
      - name: "Audit: user permissions"
        run: |
          echo "Audit: Execution by ${{ github.triggering_actor }} with ${{ steps.userPermissions.outputs.user-permission }} permissions"


  lint:
    needs:
      - get-php-info
      - validate-user-permissions
    name: "Lint"
    uses: "./.github/workflows/shared-lint.yml"
    with:
      operating-system: ubuntu-latest
      php-version: ${{ needs.get-php-info.outputs.lowest-version }}
      php-extensions: ${{ needs.get-php-info.outputs.extensions }}


  test:
    needs:
      - get-php-info
      - validate-user-permissions
      - lint
    name: "Test"
    uses: "./.github/workflows/shared-test.yml"
    with:
      operating-systems: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      php-versions: ${{ needs.get-php-info.outputs.versions }}
      php-extensions: ${{ needs.get-php-info.outputs.extensions }}
    secrets:
      geonames-username: ${{ secrets.GEONAMES_USERNAME }}
